---
namespace: cyberbullying-namespace

frontend:
  image: apinyarr/doct-cbd3375-frontend
  tag: v1.0
  service:
    type: LoadBalancer
  backend: https://tn7ysl0ig5.execute-api.ca-central-1.amazonaws.com/cyberbullyingpredict